.echo on

.header on
.mode column
SELECT * FROM COMPANY;

UPDATE COMPANY SET ADDRESS = 'Texas' WHERE ID = 6;

SELECT * FROM COMPANY;

UPDATE COMPANY SET ADDRESS = 'Texas', SALARY = 20000.00;

SELECT * FROM COMPANY;
